/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 * Copyright 2011 OpenConcerto, by ILM Informatique. All rights reserved.
 * 
 * The contents of this file are subject to the terms of the GNU General Public License Version 3
 * only ("GPL"). You may not use this file except in compliance with the License. You can obtain a
 * copy of the License at http://www.gnu.org/licenses/gpl-3.0.html See the License for the specific
 * language governing permissions and limitations under the License.
 * 
 * When distributing the software, include this License Header Notice in each file.
 */
 
 package org.openconcerto.erp.config;

import org.openconcerto.sql.model.SQLRowValues;
import org.openconcerto.sql.model.SQLTable;
import org.openconcerto.utils.Tuple2;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class DsnUrssafCode {

    final List<Tuple2<String, String>> l;

    public DsnUrssafCode() {
        l = new ArrayList<Tuple2<String, String>>();
        l.add(Tuple2.create("004", "DEDUCTION PATRONALE HEURES SUP 20 SALARIES AU +"));
        l.add(Tuple2.create("006", "ARBITRES ET JUGES SPORTIFS"));
        l.add(Tuple2.create("006", "ARBITRES ET JUGES SPORTIFS"));
        l.add(Tuple2.create("008", "CONTRAT PROFESSIONNALISATION EXO AT"));
        l.add(Tuple2.create("008", "CONTRAT PROFESSIONNALISATION EXO AT"));
        l.add(Tuple2.create("010", "CONTR RETRAITE SUPPL RENTES 32%"));
        l.add(Tuple2.create("011", "NON RESIDENTS ACTIFS EDF AGENTS STAT"));
        l.add(Tuple2.create("012", "FORFAIT SOCIAL TAUX 20 %"));
        l.add(Tuple2.create("022", "CONTRI. ADDIT. SOLIDARITE AUTONOMIE"));
        l.add(Tuple2.create("023", "ELUS LOCAUX LFSS 2013"));
        l.add(Tuple2.create("023", "ELUS LOCAUX LFSS 2013"));
        l.add(Tuple2.create("026", "CONTRAT PROF. NOTARIAT"));
        l.add(Tuple2.create("027", "CONTRIBUTION AU DIALOGUE SOCIAL"));
        l.add(Tuple2.create("030", "COTISATION AF SNCF"));
        l.add(Tuple2.create("031", "COTISATION AF RATP"));
        l.add(Tuple2.create("046", "DETENUS REGIE DIRECTE MALADIE"));
        l.add(Tuple2.create("046", "DETENUS REGIE DIRECTE MALADIE"));
        l.add(Tuple2.create("048", "DETENUS REGIE DIRECTE VIEILLESSE"));
        l.add(Tuple2.create("048", "DETENUS REGIE DIRECTE VIEILLESSE"));
        l.add(Tuple2.create("049", "AGENT TITULAIRE BANQUE DE FRANCE"));
        l.add(Tuple2.create("056", "MAITRE DOCUMENT.PRIV AV/AF"));
        l.add(Tuple2.create("056", "MAITRE DOCUMENT.PRIV AV/AF"));
        l.add(Tuple2.create("058", "MAITRE DOCUMENTALISTE PRIVE MALADIE"));
        l.add(Tuple2.create("059", "MAITRE PRIVE ALS.MOSELLE PRERETRAITE AL"));
        l.add(Tuple2.create("074", "ABATTEMENT AF 50%"));
        l.add(Tuple2.create("075", "ABATTEMENT AF 100%"));
        l.add(Tuple2.create("091", "EXONERATION AF ARMEMENT MARITIME"));
        l.add(Tuple2.create("100", "RG CAS GENERAL"));
        l.add(Tuple2.create("100", "RG CAS GENERAL"));
        l.add(Tuple2.create("102", "RG SANS AT DONT AUXILIAIRE PTT OU CL"));
        l.add(Tuple2.create("102", "RG SANS AT DONT AUXILIAIRE PTT OU CL"));
        l.add(Tuple2.create("104", "RG AVEC DISPENSE PO(AU PAIR)"));
        l.add(Tuple2.create("104", "RG AVEC DISPENSE PO(AU PAIR)"));
        l.add(Tuple2.create("106", "RG AVEC DISPENSE PO SANS AT"));
        l.add(Tuple2.create("106", "RG AVEC DISPENSE PO SANS AT"));
        l.add(Tuple2.create("109", "C.C.I.DE PARIS"));
        l.add(Tuple2.create("109", "C.C.I.DE PARIS"));
        l.add(Tuple2.create("110", "PLAN EMPLOI JEUNES"));
        l.add(Tuple2.create("110", "PLAN EMPLOI JEUNES"));
        l.add(Tuple2.create("112", "RG AVEC DISPENSE PO VIEILLESSE"));
        l.add(Tuple2.create("112", "RG AVEC DISPENSE PO VIEILLESSE"));
        l.add(Tuple2.create("114", "RG AVEC DISPENSE PO VIEIL.SANS AT"));
        l.add(Tuple2.create("114", "RG AVEC DISPENSE PO VIEIL.SANS AT"));
        l.add(Tuple2.create("116", "CONVENTION CONVERSION TEMPS PARTIEL"));
        l.add(Tuple2.create("116", "CONVENTION CONVERSION TEMPS PARTIEL"));
        l.add(Tuple2.create("118", "CONTR RET SUPPL FINAN DOT AUX PROV"));
        l.add(Tuple2.create("120", "HEBERGEMENT CENTRES READAPT SOCIALE"));
        l.add(Tuple2.create("120", "HEBERGEMENT CENTRES READAPT SOCIALE"));
        l.add(Tuple2.create("122", "HANDICAPES AVEC AIDE AU POSTE"));
        l.add(Tuple2.create("122", "HANDICAPES AVEC AIDE AU POSTE"));
        l.add(Tuple2.create("124", "VOLONTARIAT CIVIL"));
        l.add(Tuple2.create("125", "ACTIVITES ECONOMIQUES REDUITES"));
        l.add(Tuple2.create("125", "ACTIVITES ECONOMIQUES REDUITES"));
        l.add(Tuple2.create("130", "CONCIERGES ET EMPLOYES IMM.CAS GEN."));
        l.add(Tuple2.create("130", "CONCIERGES ET EMPLOYES IMM.CAS GEN."));
        l.add(Tuple2.create("131", "CONCIERGES ET EMPLOYES IMM.CAS GEN. AL"));
        l.add(Tuple2.create("131", "CONCIERGES ET EMPLOYES IMM.CAS GEN. AL"));
        l.add(Tuple2.create("132", "CONCIERGE,EMPLOYE IMMEUBLE,AU PAIR"));
        l.add(Tuple2.create("132", "CONCIERGE,EMPLOYE IMMEUBLE,AU PAIR"));
        l.add(Tuple2.create("133", "CONCIERGES EMPL.D'IMM.AU PAIR AL"));
        l.add(Tuple2.create("133", "CONCIERGES EMPL.D'IMM.AU PAIR AL"));
        l.add(Tuple2.create("134", "CENTRES DE VACANCES LEGERS"));
        l.add(Tuple2.create("134", "CENTRES DE VACANCES LEGERS"));
        l.add(Tuple2.create("135", "CENTRES DE VACANCES LEGERS AL"));
        l.add(Tuple2.create("135", "CENTRES DE VACANCES LEGERS AL"));
        l.add(Tuple2.create("136", "CENTRES VACANCES LEGERS DISPENSE PO"));
        l.add(Tuple2.create("136", "CENTRES VACANCES LEGERS DISPENSE PO"));
        l.add(Tuple2.create("137", "CENTRES VACANCES LEGERS DISP.PO AL"));
        l.add(Tuple2.create("137", "CENTRES VACANCES LEGERS DISP.PO AL"));
        l.add(Tuple2.create("138", "CENTRE VACANCES LEGER DISP.PO VIEIL."));
        l.add(Tuple2.create("138", "CENTRE VACANCES LEGER DISP.PO VIEIL."));
        l.add(Tuple2.create("139", "CENTRES VACANCES LEGERS DISP.PO VIE. AL"));
        l.add(Tuple2.create("139", "CENTRES VACANCES LEGERS DISP.PO VIE. AL"));
        l.add(Tuple2.create("140", "CENTRES DE VACANCES DEVELOPPES"));
        l.add(Tuple2.create("140", "CENTRES DE VACANCES DEVELOPPES"));
        l.add(Tuple2.create("141", "CENTRES DE VACANCES DEVELOPPES AL"));
        l.add(Tuple2.create("141", "CENTRES DE VACANCES DEVELOPPES AL"));
        l.add(Tuple2.create("142", "CENTRES VACANCES DEVEL.DISPENSE PO"));
        l.add(Tuple2.create("142", "CENTRES VACANCES DEVEL.DISPENSE PO"));
        l.add(Tuple2.create("143", "CENTRES VACANCES DEVEL.DISP.PO AL"));
        l.add(Tuple2.create("143", "CENTRES VACANCES DEVEL.DISP.PO AL"));
        l.add(Tuple2.create("144", "CENTRE VACANCES DEVEL.DISP.PO VIEIL."));
        l.add(Tuple2.create("144", "CENTRE VACANCES DEVEL.DISP.PO VIEIL."));
        l.add(Tuple2.create("145", "CENTRES VACANCES DEVEL DISP PO VIEI. AL"));
        l.add(Tuple2.create("145", "CENTRES VACANCES DEVEL DISP PO VIEI. AL"));
        l.add(Tuple2.create("146", "CADETS DE GOLF"));
        l.add(Tuple2.create("146", "CADETS DE GOLF"));
        l.add(Tuple2.create("148", "CHANSONNIERS A TEMPS PARTIEL"));
        l.add(Tuple2.create("148", "CHANSONNIERS A TEMPS PARTIEL"));
        l.add(Tuple2.create("149", "CHANSONNIERS A TEMPS PARTIEL AL"));
        l.add(Tuple2.create("149", "CHANSONNIERS A TEMPS PARTIEL AL"));
        l.add(Tuple2.create("150", "STAGIAIRES FORMATION PROFESSIONNELLE"));
        l.add(Tuple2.create("150", "STAGIAIRES FORMATION PROFESSIONNELLE"));
        l.add(Tuple2.create("152", "ENQUETES SONDAGE INSEE RECENSEMENT"));
        l.add(Tuple2.create("152", "ENQUETES SONDAGE INSEE RECENSEMENT"));
        l.add(Tuple2.create("153", "ENQUETES SONDAGE INSEE RECENSEMENT AL"));
        l.add(Tuple2.create("153", "ENQUETES SONDAGE INSEE RECENSEMENT AL"));
        l.add(Tuple2.create("154", "ENQUETES AGRICOLES,ENTR. DE SONDAGE"));
        l.add(Tuple2.create("154", "ENQUETES AGRICOLES,ENTR. DE SONDAGE"));
        l.add(Tuple2.create("156", "TACHES D'INTERET GENERAL (REMUNERES)"));
        l.add(Tuple2.create("156", "TACHES D'INTERET GENERAL (REMUNERES)"));
        l.add(Tuple2.create("158", "TACHE INTERET GENERAL(NON REMUNERES)"));
        l.add(Tuple2.create("159", "TRAVAIL D'INTERET GENERAL"));
        l.add(Tuple2.create("160", "RG SAUF MALADIE DONT ANCIENS MINEURS"));
        l.add(Tuple2.create("160", "RG SAUF MALADIE DONT ANCIENS MINEURS"));
        l.add(Tuple2.create("161", "AT APPRENTIS LOI 1979"));
        l.add(Tuple2.create("162", "RG SAUF INV.VIEIL.ANCIENS MINEURS"));
        l.add(Tuple2.create("164", "RG SAUF MALADIE VIEILLESSE"));
        l.add(Tuple2.create("166", "RG SAUF MALADIE VIEILLESSE SANS AT"));
        l.add(Tuple2.create("168", "RG SAUF MALADIE ET AF"));
        l.add(Tuple2.create("168", "RG SAUF MALADIE ET AF"));
        l.add(Tuple2.create("169", "REPORT COTIS PME DE CROISSANCE"));
        l.add(Tuple2.create("170", "RG SAUF MALADIE ET AF SANS AT"));
        l.add(Tuple2.create("170", "RG SAUF MALADIE ET AF SANS AT"));
        l.add(Tuple2.create("171", "TUTEUR D'ENTREPRISE COTISATION AT"));
        l.add(Tuple2.create("172", "RG SAUF INV.VIEIL.DONT FONCT DETACHE"));
        l.add(Tuple2.create("174", "RG SAUF INVAL VIEILLESSE SANS AT"));
        l.add(Tuple2.create("176", "RG SAUF INVALIDITE VIEILLESSE ET AF"));
        l.add(Tuple2.create("178", "RG SAUF INVAL VIEILLESSE AF SANS AT"));
        l.add(Tuple2.create("180", "RG SAUF VIEIL.DONT MILITAIRE DETACHE"));
        l.add(Tuple2.create("180", "RG SAUF VIEIL.DONT MILITAIRE DETACHE"));
        l.add(Tuple2.create("182", "RG SAUF VIEILLESSE SANS AT"));
        l.add(Tuple2.create("182", "RG SAUF VIEILLESSE SANS AT"));
        l.add(Tuple2.create("184", "RG SAUF VIEIL.AF DONT ORGAN.INTERNAT"));
        l.add(Tuple2.create("184", "RG SAUF VIEIL.AF DONT ORGAN.INTERNAT"));
        l.add(Tuple2.create("186", "RG SAUF VIEIL.AF SANS AT OUVR.ETAT"));
        l.add(Tuple2.create("186", "RG SAUF VIEIL.AF SANS AT OUVR.ETAT"));
        l.add(Tuple2.create("188", "RG SAUF AF DONT ETS PUBLICS"));
        l.add(Tuple2.create("188", "RG SAUF AF DONT ETS PUBLICS"));
        l.add(Tuple2.create("190", "RG SAUF AF SANS AT DONT ETABL PUBLIC"));
        l.add(Tuple2.create("190", "RG SAUF AF SANS AT DONT ETABL PUBLIC"));
        l.add(Tuple2.create("192", "RG INVAL.VIEILLESSE SANS AT NI AF"));
        l.add(Tuple2.create("192", "RG INVAL.VIEILLESSE SANS AT NI AF"));
        l.add(Tuple2.create("193", "VOLONTARIAT ASSOCIATIF MAL.VIEIL"));
        l.add(Tuple2.create("194", "RG SAUF AF AVEC DISPENSE PO"));
        l.add(Tuple2.create("194", "RG SAUF AF AVEC DISPENSE PO"));
        l.add(Tuple2.create("196", "RG SAUF AF AVEC DISPENSE PO SANS AT"));
        l.add(Tuple2.create("196", "RG SAUF AF AVEC DISPENSE PO SANS AT"));
        l.add(Tuple2.create("197", "VOLONTARIAT ASSOCIATIF AT"));
        l.add(Tuple2.create("198", "PROFESSIONS JUDICIAIRES"));
        l.add(Tuple2.create("198", "PROFESSIONS JUDICIAIRES"));
        l.add(Tuple2.create("200", "MARINS DU COMMERCE CMAF"));
        l.add(Tuple2.create("202", "RG AVEC DISPENSE PO VIEIL.SANS AF"));
        l.add(Tuple2.create("202", "RG AVEC DISPENSE PO VIEIL.SANS AF"));
        l.add(Tuple2.create("204", "RG SAUF AF DISPENSE PO VIEIL.SANS AT"));
        l.add(Tuple2.create("204", "RG SAUF AF DISPENSE PO VIEIL.SANS AT"));
        l.add(Tuple2.create("206", "SALARIES NON RESIDENTS ACTIFS"));
        l.add(Tuple2.create("208", "TEMPS PARTIEL (COTIS.SUR ABATTEMENT)"));
        l.add(Tuple2.create("208", "TEMPS PARTIEL (COTIS.SUR ABATTEMENT)"));
        l.add(Tuple2.create("211", "MALADIE SUR ALLOCATIONS DE CHOMAGE AL"));
        l.add(Tuple2.create("212", "MALADIE PRE RETRAITE RG (PENS.SOINS)"));
        l.add(Tuple2.create("213", "MALADIE PRE RETRAITE RG (PENS.SOINS) AL"));
        l.add(Tuple2.create("214", "MALADIE PRE RETRAITE REG.SPECIAUX"));
        l.add(Tuple2.create("216", "MALADIE SUR AVANTAGES DE RETRAITE RG"));
        l.add(Tuple2.create("218", "MALADIE AVANTAGE RETRAITE REG. SPEC."));
        l.add(Tuple2.create("220", "A.F.SEULEMENT"));
        l.add(Tuple2.create("221", "PENA.ABS.CONTRAT GEN."));
        l.add(Tuple2.create("222", "VIEILLESSE SEULEMENT"));
        l.add(Tuple2.create("226", "A.T.SEULEMENT"));
        l.add(Tuple2.create("227", "COT.SUPPL.AT DEFAUT PREVENTION"));
        l.add(Tuple2.create("228", "MALADIE SEULEMENT"));
        l.add(Tuple2.create("230", "FNAL SEULEMENT"));
        l.add(Tuple2.create("231", "PENA.ABS.DOC EVAL."));
        l.add(Tuple2.create("232", "INVALIDITE SEULEMENT"));
        l.add(Tuple2.create("233", "COT.AT FORMATION PROFESSIONNELLE"));
        l.add(Tuple2.create("233", "COT.AT FORMATION PROFESSIONNELLE"));
        l.add(Tuple2.create("234", "CSG/CRDS DETENUS"));
        l.add(Tuple2.create("234", "CSG/CRDS DETENUS"));
        l.add(Tuple2.create("236", "FNAL TOTALITE"));
        l.add(Tuple2.create("238", "FNAL TEMPS PARTIEL (SALAIRE PLAFON.)"));
        l.add(Tuple2.create("239", "CAPE SANS REMUNERATION COTISATION AT"));
        l.add(Tuple2.create("240", "DETENUS EXERCANT UNE ACTIVITE"));
        l.add(Tuple2.create("240", "DETENUS EXERCANT UNE ACTIVITE"));
        l.add(Tuple2.create("242", "PUPILLES EDUCATION SURVEILLEE"));
        l.add(Tuple2.create("244", "CREATEUR ENTREPRISE COTISANT VIEIL."));
        l.add(Tuple2.create("244", "CREATEUR ENTREPRISE COTISANT VIEIL."));
        l.add(Tuple2.create("246", "ALLOCATION CONVENTION DE CONVERSION"));
        l.add(Tuple2.create("246", "ALLOCATION CONVENTION DE CONVERSION"));
        l.add(Tuple2.create("260", "CSG CRDS REGIME GENERAL"));
        l.add(Tuple2.create("260", "CSG CRDS REGIME GENERAL"));
        l.add(Tuple2.create("261", "CRDS REV.REMPL.RETRAITE"));
        l.add(Tuple2.create("262", "CSG CRDS FONCTIONNAIRES TITULAIRES"));
        l.add(Tuple2.create("262", "CSG CRDS FONCTIONNAIRES TITULAIRES"));
        l.add(Tuple2.create("264", "CSG CRDS TITULAIRES COLLECT.TERRIT"));
        l.add(Tuple2.create("264", "CSG CRDS TITULAIRES COLLECT.TERRIT"));
        l.add(Tuple2.create("265", "SERVICE CIVIQUE VOLONTARIAT AT/MP OM"));
        l.add(Tuple2.create("265", "SERVICE CIVIQUE VOLONTARIAT AT/MP OM"));
        l.add(Tuple2.create("266", "CSG REV.REMPL.RETRAITE"));
        l.add(Tuple2.create("269", "CSG DES MILITAIRES"));
        l.add(Tuple2.create("269", "CSG DES MILITAIRES"));
        l.add(Tuple2.create("271", "CRDS DES MILITAIRES"));
        l.add(Tuple2.create("274", "CSG CRDS REG.SPECIAUX (PART.ACTIF)"));
        l.add(Tuple2.create("274", "CSG CRDS REG.SPECIAUX (PART.ACTIF)"));
        l.add(Tuple2.create("275", "CSG-CRDS REGIME GENERAL RETRAITES"));
        l.add(Tuple2.create("275", "CSG-CRDS REGIME GENERAL RETRAITES"));
        l.add(Tuple2.create("276", "CSG CRDS REG SPECX(PART.RETRAITE)"));
        l.add(Tuple2.create("276", "CSG CRDS REG SPECX(PART.RETRAITE)"));
        l.add(Tuple2.create("277", "CSG REGIME GENERAL PRERETRAITES"));
        l.add(Tuple2.create("277", "CSG REGIME GENERAL PRERETRAITES"));
        l.add(Tuple2.create("278", "CSG CRDS REG.SPECX (PART.INVALIDE)"));
        l.add(Tuple2.create("278", "CSG CRDS REG.SPECX (PART.INVALIDE)"));
        l.add(Tuple2.create("279", "CSG REGIME GENERAL CHOMAGE"));
        l.add(Tuple2.create("279", "CSG REGIME GENERAL CHOMAGE"));
        l.add(Tuple2.create("283", "CSG/CRDS AVANTAGES DE PRERETRAITE"));
        l.add(Tuple2.create("283", "CSG/CRDS AVANTAGES DE PRERETRAITE"));
        l.add(Tuple2.create("284", "CSG CRDS ELUS LOCAUX"));
        l.add(Tuple2.create("284", "CSG CRDS ELUS LOCAUX"));
        l.add(Tuple2.create("285", "S.CIVIQUE VOLONTARIAT AV AF MAL OM"));
        l.add(Tuple2.create("285", "S.CIVIQUE VOLONTARIAT AV AF MAL OM"));
        l.add(Tuple2.create("286", "ARTISTES SALARIES NON RESIDENTS"));
        l.add(Tuple2.create("287", "CRDS REGIME GENERAL PRERETRAITES"));
        l.add(Tuple2.create("288", "VIEILLESSE TEMPS PARTIEL OU MAYOTTE"));
        l.add(Tuple2.create("288", "VIEILLESSE TEMPS PARTIEL OU MAYOTTE"));
        l.add(Tuple2.create("289", "CRDS REGIME GENERAL CHOMAGE"));
        l.add(Tuple2.create("293", "RG MAJO CDD 1-3M CONT. USAGE U2"));
        l.add(Tuple2.create("294", "TEMPS PARTIEL CLERCS DE NOTAIRE"));
        l.add(Tuple2.create("295", "RG MAJO CDD 1-3M ACC. ACTIV U2"));
        l.add(Tuple2.create("296", "CONTRAT ACCES EMPLOI MINISTERE DOM OM"));
        l.add(Tuple2.create("296", "CONTRAT ACCES EMPLOI MINISTERE DOM OM"));
        l.add(Tuple2.create("297", "CONTRAT ACCES EMPLOI DOM MIN.BUDGET OM"));
        l.add(Tuple2.create("297", "CONTRAT ACCES EMPLOI DOM MIN.BUDGET OM"));
        l.add(Tuple2.create("298", "CONTRAT ACCES EMPLOI MINISTERE DOM OM"));
        l.add(Tuple2.create("298", "CONTRAT ACCES EMPLOI MINISTERE DOM OM"));
        l.add(Tuple2.create("299", "CAE CAS PART MINISTERE BUDGET OM"));
        l.add(Tuple2.create("299", "CAE CAS PART MINISTERE BUDGET OM"));
        l.add(Tuple2.create("300", "CREANCE CCVRP"));
        l.add(Tuple2.create("300", "CREANCE CCVRP"));
        l.add(Tuple2.create("301", "CREANCE CCVRP AL"));
        l.add(Tuple2.create("301", "CREANCE CCVRP AL"));
        l.add(Tuple2.create("302", "EXO AIDE A DOMICILE/ACCUEIL FAMILIAL"));
        l.add(Tuple2.create("302", "EXO AIDE A DOMICILE/ACCUEIL FAMILIAL"));
        l.add(Tuple2.create("306", "NON RESIDENTS RETRAITES PRERETRAITES"));
        l.add(Tuple2.create("307", "NON RESIDENTS SUR ALLOCATION CHOMAGE"));
        l.add(Tuple2.create("308", "NON RESIDENTS RETRAITES REG. SPEC."));
        l.add(Tuple2.create("312", "ARTISTES CAS GENERAL ABATTEMENT 30%"));
        l.add(Tuple2.create("312", "ARTISTES CAS GENERAL ABATTEMENT 30%"));
        l.add(Tuple2.create("313", "ARTISTES CAS GENERAL ABATTEMENT 30% AL"));
        l.add(Tuple2.create("313", "ARTISTES CAS GENERAL ABATTEMENT 30% AL"));
        l.add(Tuple2.create("314", "ARTISTES AVEC DISPENSE PO ABATT 30%"));
        l.add(Tuple2.create("314", "ARTISTES AVEC DISPENSE PO ABATT 30%"));
        l.add(Tuple2.create("315", "ARTISTES AVEC DISPENSE PO ABATT 30% AL"));
        l.add(Tuple2.create("315", "ARTISTES AVEC DISPENSE PO ABATT 30% AL"));
        l.add(Tuple2.create("316", "FNAL ARTISTES TOTALITE"));
        l.add(Tuple2.create("317", "FNAL DEGR. ANNEE 4 ARTISTES"));
        l.add(Tuple2.create("318", "ARTISTES FONCTIONNAIRES ABATT 30%"));
        l.add(Tuple2.create("318", "ARTISTES FONCTIONNAIRES ABATT 30%"));
        l.add(Tuple2.create("319", "ARTISTES FONCTIONNAIRES ABBAT 30% AL"));
        l.add(Tuple2.create("319", "ARTISTES FONCTIONNAIRES ABBAT 30% AL"));
        l.add(Tuple2.create("320", "ARTISTES SANS AT"));
        l.add(Tuple2.create("320", "ARTISTES SANS AT"));
        l.add(Tuple2.create("321", "ARTISTES SANS AT AL"));
        l.add(Tuple2.create("321", "ARTISTES SANS AT AL"));
        l.add(Tuple2.create("323", "EXO CONTRATS AIDES ATELIER INSERTION"));
        l.add(Tuple2.create("323", "EXO CONTRATS AIDES ATELIER INSERTION"));
        l.add(Tuple2.create("327", "RG MAJO CDD 1M ACC. ACTIV U2"));
        l.add(Tuple2.create("330", "MEDECINS FONCTIONNAIRES"));
        l.add(Tuple2.create("330", "MEDECINS FONCTIONNAIRES"));
        l.add(Tuple2.create("331", "MEDECINS FONCTIONNAIRES AL"));
        l.add(Tuple2.create("331", "MEDECINS FONCTIONNAIRES AL"));
        l.add(Tuple2.create("332", "FNAL PLAFONNE"));
        l.add(Tuple2.create("333", "EXO CONTRATS AIDES POLE EMPLOI"));
        l.add(Tuple2.create("333", "EXO CONTRATS AIDES POLE EMPLOI"));
        l.add(Tuple2.create("334", "FNAL ARTISTES PLAFONNE"));
        l.add(Tuple2.create("336", "PROF MEDIC ABATT.30% PLF"));
        l.add(Tuple2.create("336", "PROF MEDIC ABATT.30% PLF"));
        l.add(Tuple2.create("338", "PROF MEDIC ABATT 30% PLF SAUF AF"));
        l.add(Tuple2.create("338", "PROF MEDIC ABATT 30% PLF SAUF AF"));
        l.add(Tuple2.create("340", "INSERTION ACCUEIL ENTREP.EXO 100%"));
        l.add(Tuple2.create("340", "INSERTION ACCUEIL ENTREP.EXO 100%"));
        l.add(Tuple2.create("343", "RG EXO COT PAT CDI - 26 ANS U2"));
        l.add(Tuple2.create("346", "PERSONNEL MEDICAL CENTRES DE SANTE"));
        l.add(Tuple2.create("346", "PERSONNEL MEDICAL CENTRES DE SANTE"));
        l.add(Tuple2.create("348", "VENTE A DOMICILE PAR DEMARCHAGE"));
        l.add(Tuple2.create("348", "VENTE A DOMICILE PAR DEMARCHAGE"));
        l.add(Tuple2.create("350", "CONTRAT D'INSERTION PAR L'ACTIVITE OM"));
        l.add(Tuple2.create("350", "CONTRAT D'INSERTION PAR L'ACTIVITE OM"));
        l.add(Tuple2.create("352", "CONTR INSERT PAR L'ACTIVITE CAS PART OM"));
        l.add(Tuple2.create("352", "CONTR INSERT PAR L'ACTIVITE CAS PART OM"));
        l.add(Tuple2.create("353", "REGUL RG MAJO CDD TAUX 0,5 % U2"));
        l.add(Tuple2.create("360", "INSERTION ACCUEIL EN STRUCT. AGREEE"));
        l.add(Tuple2.create("360", "INSERTION ACCUEIL EN STRUCT. AGREEE"));
        l.add(Tuple2.create("362", "ELEVE ENS.TECHNIQUE ART 412.8.2E(A)"));
        l.add(Tuple2.create("362", "ELEVE ENS.TECHNIQUE ART 412.8.2E(A)"));
        l.add(Tuple2.create("363", "REGUL RG MAJO CDD TAUX 1,5 % U2"));
        l.add(Tuple2.create("364", "ELEVE ENS.SECONDAIRE AR.412.8.2E(B)"));
        l.add(Tuple2.create("364", "ELEVE ENS.SECONDAIRE AR.412.8.2E(B)"));
        l.add(Tuple2.create("366", "ASSOC INTERMEDIAIRE (ACT<OU=750H)"));
        l.add(Tuple2.create("366", "ASSOC INTERMEDIAIRE (ACT<OU=750H)"));
        l.add(Tuple2.create("369", "REGUL RG MAJO CDD TAUX 3,0 % U2"));
        l.add(Tuple2.create("370", "ASSOCIATIONS INTERMEDIAIRES"));
        l.add(Tuple2.create("370", "ASSOCIATIONS INTERMEDIAIRES"));
        l.add(Tuple2.create("372", "SITUATION INSERTION,BENEFICIAIRE RMI"));
        l.add(Tuple2.create("381", "MAJO ALS MOS 1.5% - SECTEUR PRIVE AL"));
        l.add(Tuple2.create("385", "SERVICE CIVIQUE VOLONTARIAT CSG-CRDS OM"));
        l.add(Tuple2.create("385", "SERVICE CIVIQUE VOLONTARIAT CSG-CRDS OM"));
        l.add(Tuple2.create("391", "MAJO ALS MOS 1.5% - SECTEUR PUBLIC AL"));
        l.add(Tuple2.create("400", "CREDIT IMPOT COMPETITIVITE EMPLOI"));
        l.add(Tuple2.create("402", "JEU EXONERATION TAUX PLEIN"));
        l.add(Tuple2.create("402", "JEU EXONERATION TAUX PLEIN"));
        l.add(Tuple2.create("404", "CONTRAT CAPE AVEC REMUNERATION"));
        l.add(Tuple2.create("404", "CONTRAT CAPE AVEC REMUNERATION"));
        l.add(Tuple2.create("406", "CONGE INDIVIDUEL DE FORMATION"));
        l.add(Tuple2.create("406", "CONGE INDIVIDUEL DE FORMATION"));
        l.add(Tuple2.create("420", "CONTRAT ACCOMPAGNEMENT DANS L EMPLOI"));
        l.add(Tuple2.create("420", "CONTRAT ACCOMPAGNEMENT DANS L EMPLOI"));
        l.add(Tuple2.create("422", "CONTRAT ACCOMPAGNEMENT CAS PART"));
        l.add(Tuple2.create("422", "CONTRAT ACCOMPAGNEMENT CAS PART"));
        l.add(Tuple2.create("423", "CONTRIB ASSURANCE CHOMAGE APPREN 87 U2"));
        l.add(Tuple2.create("429", "CONTRIB ASSURANCE CHOMAGE APPR PUBLI U2"));
        l.add(Tuple2.create("430", "COMPLEMENT COTISATION AF"));
        l.add(Tuple2.create("432", "COMPLEMENT AF ABATT. 30 %"));
        l.add(Tuple2.create("434", "COMPLEMENT AF ABATT. 20 %"));
        l.add(Tuple2.create("437", "DEDUCTION AF TAUX REDUIT"));
        l.add(Tuple2.create("438", "EXONERATION GREVE SNCM"));
        l.add(Tuple2.create("450", "PENIBILITE COTISATION UNIVERSELLE"));
        l.add(Tuple2.create("451", "PENIBILITE COT ADDIT MONO EXPO"));
        l.add(Tuple2.create("451", "PENIBILITE COT ADDIT MONO EXPO"));
        l.add(Tuple2.create("452", "PENIBILITE COT ADDIT MULTI EXPO"));
        l.add(Tuple2.create("452", "PENIBILITE COT ADDIT MULTI EXPO"));
        l.add(Tuple2.create("455", "CONTRIB ASSURANCE CHOMAGE APPREN 79 U2"));
        l.add(Tuple2.create("455", "CONTRIB ASSURANCE CHOMAGE APPREN 79 U2"));
        l.add(Tuple2.create("456", "CONTRAT DE PROFESSIONNALISATION"));
        l.add(Tuple2.create("456", "CONTRAT DE PROFESSIONNALISATION"));
        l.add(Tuple2.create("458", "CONTRAT PROF. CAS PARTICULIER"));
        l.add(Tuple2.create("458", "CONTRAT PROF. CAS PARTICULIER"));
        l.add(Tuple2.create("459", "CMAF CONTRAT DE PROFESSIONNALISATION"));
        l.add(Tuple2.create("460", "RG SAUF VIEILL.NATIONALITE ETRANGERE"));
        l.add(Tuple2.create("460", "RG SAUF VIEILL.NATIONALITE ETRANGERE"));
        l.add(Tuple2.create("462", "EXO PP DOM SMIC 130% A 230% OM"));
        l.add(Tuple2.create("463", "EXO PP DOM SMIC 170% A 350% OM"));
        l.add(Tuple2.create("464", "EXONERATION COLPORTEURS DE PRESSE"));
        l.add(Tuple2.create("464", "EXONERATION COLPORTEURS DE PRESSE"));
        l.add(Tuple2.create("466", "EXONERATION PRESSE MAGAZINE"));
        l.add(Tuple2.create("466", "EXONERATION PRESSE MAGAZINE"));
        l.add(Tuple2.create("467", "EXONERATION PRESSE MAGAZINE AL"));
        l.add(Tuple2.create("467", "EXONERATION PRESSE MAGAZINE AL"));
        l.add(Tuple2.create("468", "EXONERATION PRESSE GRATUITE"));
        l.add(Tuple2.create("468", "EXONERATION PRESSE GRATUITE"));
        l.add(Tuple2.create("470", "EXONERATION PRESSE GRATUITE AL"));
        l.add(Tuple2.create("470", "EXONERATION PRESSE GRATUITE AL"));
        l.add(Tuple2.create("472", "EXO PP DOM SMIC DE 140% A 300% OM"));
        l.add(Tuple2.create("473", "EXO PP DOM SMIC DE 170% A 450% OM"));
        l.add(Tuple2.create("478", "REGULARISATION FORFAIT SOCIAL"));
        l.add(Tuple2.create("479", "FORFAIT SOCIAL 8%"));
        l.add(Tuple2.create("479", "FORFAIT SOCIAL 8%"));
        l.add(Tuple2.create("480", "FORFAIT SOCIAL TAUX 16%"));
        l.add(Tuple2.create("496", "COTISATIONS AGS ETT INTERIMAIRES U2"));
        l.add(Tuple2.create("513", "EMBAUCHE 1ER AU 50EME SALARIE ZRR"));
        l.add(Tuple2.create("532", "CONTRIBUTION ADD. RETRAITE SUPPL"));
        l.add(Tuple2.create("536", "FNAL DEGR.ANNEE 4 CAS GENERAL+SECT.P"));
        l.add(Tuple2.create("540", "FNAL DEGRE ANNEE 5 CAS GENERAL   SEC"));
        l.add(Tuple2.create("542", "FNAL DEGRE ANNEE 6 CAS GENERAL + SEC"));
        l.add(Tuple2.create("542", "FNAL DEGRE ANNEE 6 CAS GENERAL + SEC"));
        l.add(Tuple2.create("544", "CONTR.SOUSCRIPTION ATTRIB.ACTIONS"));
        l.add(Tuple2.create("544", "CONTR.SOUSCRIPTION ATTRIB.ACTIONS"));
        l.add(Tuple2.create("546", "CONTR.RETR.SUPPL BENEF. RENTES 21%"));
        l.add(Tuple2.create("548", "CAISSES CP SECT BAT TP-METROPOLE"));
        l.add(Tuple2.create("548", "CAISSES CP SECT BAT TP-METROPOLE"));
        l.add(Tuple2.create("549", "CAISSES CP SECT BAT TP - DOM OM"));
        l.add(Tuple2.create("549", "CAISSES CP SECT BAT TP - DOM OM"));
        l.add(Tuple2.create("550", "CAISSES CP AUTRES SECTEURS"));
        l.add(Tuple2.create("550", "CAISSES CP AUTRES SECTEURS"));
        l.add(Tuple2.create("551", "CONTRIB ATTRIB ACTIONS GRATUITES"));
        l.add(Tuple2.create("551", "CONTRIB ATTRIB ACTIONS GRATUITES"));
        l.add(Tuple2.create("564", "CONTR.RETR.SUPPL BENEF.RENTES 7%"));
        l.add(Tuple2.create("566", "CONTR.RETR.SUPPL BENEF.RENTES 14%"));
        l.add(Tuple2.create("583", "SERVICE CIVIQUE ENGAGEMENT AT/MP"));
        l.add(Tuple2.create("583", "SERVICE CIVIQUE ENGAGEMENT AT/MP"));
        l.add(Tuple2.create("585", "S.CIVIQUE ENGAGEMENT AV AF MAL"));
        l.add(Tuple2.create("585", "S.CIVIQUE ENGAGEMENT AV AF MAL"));
        l.add(Tuple2.create("586", "SERVICE CIVIQUE ENGAGEMENT CSG-CRDS"));
        l.add(Tuple2.create("586", "SERVICE CIVIQUE ENGAGEMENT CSG-CRDS"));
        l.add(Tuple2.create("588", "SERVICE CIVIQUE VOLONTARIAT AT/MP"));
        l.add(Tuple2.create("588", "SERVICE CIVIQUE VOLONTARIAT AT/MP"));
        l.add(Tuple2.create("592", "S.CIVIQUE VOLONTARIAT AV AF MAL"));
        l.add(Tuple2.create("592", "S.CIVIQUE VOLONTARIAT AV AF MAL"));
        l.add(Tuple2.create("593", "EXONERATION ZRD"));
        l.add(Tuple2.create("594", "SERVICE CIVIQUE VOLONTARIAT CSG-CRDS"));
        l.add(Tuple2.create("594", "SERVICE CIVIQUE VOLONTARIAT CSG-CRDS"));
        l.add(Tuple2.create("595", "EXO DEGRESSIVE OIG ZRR COT SS"));
        l.add(Tuple2.create("597", "EXO DEGRESSIVE OIG ZRR FNAL"));
        l.add(Tuple2.create("599", "EXO DEGR OIG ZRR TAXE SYND MIXTE"));
        l.add(Tuple2.create("601", "EXO DEGR OIG ZRR VERST TRANSPORT"));
        l.add(Tuple2.create("603", "AT FONDS COMMUN L437.1 CSS"));
        l.add(Tuple2.create("605", "ESEF - RG CAS GENERAL"));
        l.add(Tuple2.create("605", "ESEF - RG CAS GENERAL"));
        l.add(Tuple2.create("622", "CPRPSNCF NON CADRES SUPERIEURS"));
        l.add(Tuple2.create("623", "CPRPSNCF CADRES SUPERIEURS"));
        l.add(Tuple2.create("624", "CPRPSNCF NON CADRE SUP NON RESIDENT"));
        l.add(Tuple2.create("625", "CPRPSNCF CADRES SUP NON RESIDENTS"));
        l.add(Tuple2.create("626", "EXO COMPTE EPARGNE TEMPS VERS PERCO"));
        l.add(Tuple2.create("628", "JOURNALISTES ABATT 20% AT/AV/AF/VT"));
        l.add(Tuple2.create("628", "JOURNALISTES ABATT 20% AT/AV/AF/VT"));
        l.add(Tuple2.create("630", "CPRPSNCF CPA CADRES SUP"));
        l.add(Tuple2.create("630", "CPRPSNCF CPA CADRES SUP"));
        l.add(Tuple2.create("631", "CPRPSNCF CPA NON CADRES SUP"));
        l.add(Tuple2.create("631", "CPRPSNCF CPA NON CADRES SUP"));
        l.add(Tuple2.create("632", "CPRPSNCF TEMPS PARTIEL CADRES SUP"));
        l.add(Tuple2.create("632", "CPRPSNCF TEMPS PARTIEL CADRES SUP"));
        l.add(Tuple2.create("633", "CPRPSNCF TEMPS PARTIEL NON CADRES SU"));
        l.add(Tuple2.create("633", "CPRPSNCF TEMPS PARTIEL NON CADRES SU"));
        l.add(Tuple2.create("634", "CPRPSNCF PREVOYANCE AGENTS RETRAITES"));
        l.add(Tuple2.create("639", "CPRPSNCF APPRENTIS A COMPTER 010708"));
        l.add(Tuple2.create("642", "CPRPSNCF RETRAITE NON CADRES SUP"));
        l.add(Tuple2.create("642", "CPRPSNCF RETRAITE NON CADRES SUP"));
        l.add(Tuple2.create("643", "CPRPSNCF RETRAITE CADRES SUP"));
        l.add(Tuple2.create("643", "CPRPSNCF RETRAITE CADRES SUP"));
        l.add(Tuple2.create("671", "REDUCTION GENERALE"));
        l.add(Tuple2.create("673", "ZFU OU ASS ZFU/ZRU COT SS+FNAL 0.10%"));
        l.add(Tuple2.create("674", "ZFU OU ASS ZFU/ZRU FNAL"));
        l.add(Tuple2.create("675", "ZFU OU ASS ZFU/ZRU VERST TRANSPORT"));
        l.add(Tuple2.create("695", "CSG/CRDS CHEQUE VACANCES"));
        l.add(Tuple2.create("695", "CSG/CRDS CHEQUE VACANCES"));
        l.add(Tuple2.create("701", "APPRENTIS LOI 1987 AVEC AT"));
        l.add(Tuple2.create("702", "RG SANCTION NON RESPECT N.A.O"));
        l.add(Tuple2.create("703", "APPRENTIS LOI 1987 AVEC AT AL"));
        l.add(Tuple2.create("704", "CONTR RET SUPPL FINAN PRIMES"));
        l.add(Tuple2.create("705", "APPRENTIS LOI 87 AVEC AT"));
        l.add(Tuple2.create("706", "CONTR RETRAITE SUPPL RENTES"));
        l.add(Tuple2.create("707", "APPRENTIS LOI 87 AVEC AT AL"));
        l.add(Tuple2.create("712", "ASSISTANTS EDUCATION TEMPS COMPLET"));
        l.add(Tuple2.create("712", "ASSISTANTS EDUCATION TEMPS COMPLET"));
        l.add(Tuple2.create("714", "ASSISTANTS EDUCATION AVEC AT"));
        l.add(Tuple2.create("714", "ASSISTANTS EDUCATION AVEC AT"));
        l.add(Tuple2.create("715", "ASSISTANTS EDUCATION AVEC AT AL"));
        l.add(Tuple2.create("715", "ASSISTANTS EDUCATION AVEC AT AL"));
        l.add(Tuple2.create("716", "CONTRIBUTION PATRONALE PRERETRAITES"));
        l.add(Tuple2.create("716", "CONTRIBUTION PATRONALE PRERETRAITES"));
        l.add(Tuple2.create("717", "CONTRIBUTION PATRONALE PRERETRAITES"));
        l.add(Tuple2.create("719", "CONTRIB.INDEMNITE MISE A LA RETRAITE"));
        l.add(Tuple2.create("734", "JEI EXONERATION TAUX PLEIN"));
        l.add(Tuple2.create("734", "JEI EXONERATION TAUX PLEIN"));
        l.add(Tuple2.create("737", "LOI INITIATIVE ECO REPORT PREVOYANCE"));
        l.add(Tuple2.create("741", "REPORT LOI INITIATIVE ECONOMIQUE"));
        l.add(Tuple2.create("743", "LOI INITIAT ECO REPORT TAXE SYND MXT"));
        l.add(Tuple2.create("749", "LOI INITIATIVE ECO REPORT TRANSPORT"));
        l.add(Tuple2.create("754", "GUS TOREROS ABT 30%"));
        l.add(Tuple2.create("754", "GUS TOREROS ABT 30%"));
        l.add(Tuple2.create("755", "BASSINS D'EMPLOI A REDYNAMISER"));
        l.add(Tuple2.create("755", "BASSINS D'EMPLOI A REDYNAMISER"));
        l.add(Tuple2.create("772", "CONTRIBUTIONS ASSURANCE CHOMAGE U2"));
        l.add(Tuple2.create("773", "ZFU OU ASS ZFU/ZRU SYND.MIXTE"));
        l.add(Tuple2.create("776", "DOM PECHE MARITIME EXO CSG-CRDS OM"));
        l.add(Tuple2.create("777", "DOM PECHE MARITIME EXO AF 50% OM"));
        l.add(Tuple2.create("780", "DOM PECHE EXO EN % DU SMIC OM"));
        l.add(Tuple2.create("789", "CMAF ACCRE CHOMEUR"));
        l.add(Tuple2.create("790", "CMAF ACCRE RMI"));
        l.add(Tuple2.create("800", "CHANGEMENT OPTION REGULARISATION"));
        l.add(Tuple2.create("801", "REGUL. REDUCTION GENERALE"));
        l.add(Tuple2.create("802", "REM.VERSEES PAR TIERS CONTRIB.LIBERA"));
        l.add(Tuple2.create("802", "REM.VERSEES PAR TIERS CONTRIB.LIBERA"));
        l.add(Tuple2.create("803", "APPRENTIS LOI 1992 AVEC AT"));
        l.add(Tuple2.create("804", "REMUNERATIONS VERSEES PAR DES TIERS"));
        l.add(Tuple2.create("804", "REMUNERATIONS VERSEES PAR DES TIERS"));
        l.add(Tuple2.create("805", "APPRENTIS LOI 1992 AVEC AT AL"));
        l.add(Tuple2.create("807", "FNAL DEGRE ANNEE 5 ARTISTES"));
        l.add(Tuple2.create("808", "FNAL DEGRE ANNEE 5 JOURNALISTES"));
        l.add(Tuple2.create("809", "FNAL DEGRE ANNEE 5 MEDECINS"));
        l.add(Tuple2.create("811", "REM.VERSEES PAR TIERS CONTRIB.LIBERA AL"));
        l.add(Tuple2.create("811", "REM.VERSEES PAR TIERS CONTRIB.LIBERA AL"));
        l.add(Tuple2.create("814", "FNAL DEGRE ANNEE 6 ARTISTES"));
        l.add(Tuple2.create("814", "FNAL DEGRE ANNEE 6 ARTISTES"));
        l.add(Tuple2.create("815", "APPRENTIS LOI 1992 AVEC AT"));
        l.add(Tuple2.create("816", "FNAL DEGRE ANNEE 6 JOURNALISTES"));
        l.add(Tuple2.create("817", "APPRENTIS LOI 1992 AVEC AT AL"));
        l.add(Tuple2.create("823", "COLLABORATEUR OCCAS SERVICE PUBLIC"));
        l.add(Tuple2.create("823", "COLLABORATEUR OCCAS SERVICE PUBLIC"));
        l.add(Tuple2.create("830", "APPRENTIS 87 FNAL DEG 4 ANNEE"));
        l.add(Tuple2.create("832", "APPRENTIS 87 FNAL DEG 5 ANNEE"));
        l.add(Tuple2.create("834", "APPRENTIS 87 FNAL DEG 6 ANNEE"));
        l.add(Tuple2.create("835", "VOLONTARIAT POUR L'INSERTION"));
        l.add(Tuple2.create("837", "CSG CRDS VOLONTARIAT INSERTION EXO"));
        l.add(Tuple2.create("842", "COMPTE GLOBAL CAIS.CONGES PAYES BT"));
        l.add(Tuple2.create("842", "COMPTE GLOBAL CAIS.CONGES PAYES BT"));
        l.add(Tuple2.create("849", "CPRPSNCF CONTRAT PROF 45 ANS ET PLUS"));
        l.add(Tuple2.create("849", "CPRPSNCF CONTRAT PROF 45 ANS ET PLUS"));
        l.add(Tuple2.create("850", "FONCT.TITULAIRES OUVRIERS D'ETAT"));
        l.add(Tuple2.create("852", "FONCTIONNAIRES NON TITUL FP AVEC AF"));
        l.add(Tuple2.create("852", "FONCTIONNAIRES NON TITUL FP AVEC AF"));
        l.add(Tuple2.create("854", "FONCTIONNAIRES NON TITUL FP SAUF AF"));
        l.add(Tuple2.create("854", "FONCTIONNAIRES NON TITUL FP SAUF AF"));
        l.add(Tuple2.create("856", "FONCT.DETACHE SAUF AF AT BUDG.ANNEXE"));
        l.add(Tuple2.create("858", "FONCT DETACHES NELLE CALEDONIE"));
        l.add(Tuple2.create("860", "FONCT.DETACHES AVEC AF SANS AT"));
        l.add(Tuple2.create("862", "FONCT.TERRES AUSTRALES FRANCAISES"));
        l.add(Tuple2.create("863", "RG MANDATAIRES SOCIAUX"));
        l.add(Tuple2.create("863", "RG MANDATAIRES SOCIAUX"));
        l.add(Tuple2.create("864", "CNRACT CESS. PROGRES. ACTIV.AVEC AT"));
        l.add(Tuple2.create("866", "CNRACT CESS. PROGRES. ACTIV.SANS AT"));
        l.add(Tuple2.create("868", "POSTES TELECOM ESPACE PERS TITULAIRE"));
        l.add(Tuple2.create("870", "EDF GDF AGENTS STATUTAIRES"));
        l.add(Tuple2.create("871", "PORT AUTONOME DE STRASBOURG AL"));
        l.add(Tuple2.create("872", "EDF GDF AGENTS DETACHES MUTUELLE"));
        l.add(Tuple2.create("874", "FONCT.TIT.DET.C T NON PERM SANS AT"));
        l.add(Tuple2.create("876", "FONCT.TIT.DET.C T NON PERM.AVEC AT"));
        l.add(Tuple2.create("878", "FONCTIONNAIRES TITUL DOM ETRANGER OM"));
        l.add(Tuple2.create("879", "COTISATION AF MILITAIRES"));
        l.add(Tuple2.create("880", "CNRACT AVEC AT"));
        l.add(Tuple2.create("882", "CNRACT SANS AT"));
        l.add(Tuple2.create("884", "CNRACT SAUF AF SANS AT"));
        l.add(Tuple2.create("886", "ELUS LOCAUX LETTRES COLL.54 ET 66"));
        l.add(Tuple2.create("886", "ELUS LOCAUX LETTRES COLL.54 ET 66"));
        l.add(Tuple2.create("888", "CTRES COMM ACTION SOC.SANS AT EXO"));
        l.add(Tuple2.create("890", "CENTRES COMMUNAUX ACTION SOC AVEC AT"));
        l.add(Tuple2.create("892", "FONCT.SUR BUDGETS ANNEXES SANS AT"));
        l.add(Tuple2.create("893", "FONCT REMUNERE BUDG ANNEXE SANS AT AL"));
        l.add(Tuple2.create("894", "FONCT.SUR BUDGETS ANNEXES AVEC AT"));
        l.add(Tuple2.create("897", "EXO ASS CHOMAGE ARMEMENT MARITIME U2"));
        l.add(Tuple2.create("899", "PORT AUTON. STRASBOURG TPS PARTIEL AL"));
        l.add(Tuple2.create("900", "TRANSPORT"));
        l.add(Tuple2.create("901", "TAXE SYNDICAT MIXTE TRANSPORT"));
        l.add(Tuple2.create("909", "COT.AT FORFAIT.INOBS.MESURES PREV."));
        l.add(Tuple2.create("911", "TRANSPORT JOURNALISTES TX MINORE 20%"));
        l.add(Tuple2.create("917", "SYND MIXTE JOURNALISTES TX MINORE 20"));
        l.add(Tuple2.create("920", "EMPL AGRIC (1500 TONNES CANNE) RMI OM"));
        l.add(Tuple2.create("920", "EMPL AGRIC (1500 TONNES CANNE) RMI OM"));
        l.add(Tuple2.create("921", "TRANSPORT ARTISTES TX MINORE 30%"));
        l.add(Tuple2.create("922", "ENTR.DE PRODUCTION D ELECTRICITE"));
        l.add(Tuple2.create("922", "ENTR.DE PRODUCTION D ELECTRICITE"));
        l.add(Tuple2.create("926", "AT SEULEMENT - GESTION TOTALE"));
        l.add(Tuple2.create("927", "SYNDICAT MIXTE ARTISTES TX MINORE30%"));
        l.add(Tuple2.create("937", "COTISATIONS AGS CAS GENERAL U2"));
        l.add(Tuple2.create("937", "COTISATIONS AGS CAS GENERAL U2"));
        l.add(Tuple2.create("938", "CONTRATS AIDES ATELIER INSERTION"));
        l.add(Tuple2.create("938", "CONTRATS AIDES ATELIER INSERTION"));
        l.add(Tuple2.create("941", "CSG REV.REMPL.PRERETRAITE"));
        l.add(Tuple2.create("942", "CSG REV.REMPL.CHOMAGE"));
        l.add(Tuple2.create("948", "CONTRAT EMPLOI SOLIDARITE"));
        l.add(Tuple2.create("948", "CONTRAT EMPLOI SOLIDARITE"));
        l.add(Tuple2.create("950", "CONTRAT EMPLOI SOLIDARITE CAS PART"));
        l.add(Tuple2.create("950", "CONTRAT EMPLOI SOLIDARITE CAS PART"));
        l.add(Tuple2.create("951", "CONTRATS EMPLOI SOLIDARITE CAS PART"));
        l.add(Tuple2.create("951", "CONTRATS EMPLOI SOLIDARITE CAS PART"));
        l.add(Tuple2.create("952", "CONTRAT EMPLOI CONSOLIDE CAS GENERAL"));
        l.add(Tuple2.create("952", "CONTRAT EMPLOI CONSOLIDE CAS GENERAL"));
        l.add(Tuple2.create("954", "CONTRAT EMPLOI CONSOLIDE CAS PART"));
        l.add(Tuple2.create("954", "CONTRAT EMPLOI CONSOLIDE CAS PART"));
        l.add(Tuple2.create("963", "CONT.PROFESSIONNALISATION AVEC AT"));
        l.add(Tuple2.create("963", "CONT.PROFESSIONNALISATION AVEC AT"));
        l.add(Tuple2.create("964", "EXO ACCRE BENEFICIAIRE DU RMI"));
        l.add(Tuple2.create("966", "EXO ACCRE BENEFIC. RMI CAS PART."));
        l.add(Tuple2.create("967", "CONTR.ROYALTIES ART.ET MANNEQUINS"));
        l.add(Tuple2.create("967", "CONTR.ROYALTIES ART.ET MANNEQUINS"));
        l.add(Tuple2.create("968", "EXO ACCRE CHOMEUR NON INDEMNISE"));
        l.add(Tuple2.create("969", "COT.MAL.ROYALTIES ART.ETRANGER"));
        l.add(Tuple2.create("969", "COT.MAL.ROYALTIES ART.ETRANGER"));
        l.add(Tuple2.create("970", "EXONERATION ACCRE CHOMEUR CAS PART"));
        l.add(Tuple2.create("984", "EXO ACCRE AUTRES BENEFICIAIRES"));
        l.add(Tuple2.create("985", "PENALITE PENIBILITE"));
    }

    public List<Tuple2<String, String>> getCodes() {
        return l;
    }

    public void insertCode(SQLTable table) throws SQLException {

        for (Tuple2<String, String> tuple2 : l) {
            SQLRowValues rowVals = new SQLRowValues(table);
            rowVals.put("CODE", tuple2.get0());
            rowVals.put("NOM", tuple2.get1());
            rowVals.put("CAISSE_COTISATION", "URSSAF");
            rowVals.insert();
        }
    }

}
